#!/bin/bash

set -e;
echo "Cleaning and creating 'repos' dir"
rm -rf repos;
mkdir repos;
cd repos;

echo "Fetching aragon client and installing dependencies"
git clone https://github.com/aragon/aragon.git -b master;
cd aragon;
npm i;