#!/bin/bash

set -e;

echo "Fetching dao-templates and installing dependencies (this may also take a while 😉)"

cd repos;
git clone https://github.com/aragon/dao-templates.git -b master;
cd dao-templates;
npm run bootstrap -- --no-ci;
cd ..;
