#!/bin/bash

set -e;

echo "Fetching dao-templates and installing dependencies (this may also take a while 😉)"
git clone https://github.com/aragon/dao-templates.git -b master;
cd dao-templates;
npm i;
cd ..;
