#!/bin/bash

set -e;

echo "Fetching fundraising and installing dependencies (this may take a while 😉)"

cd repos;
git clone https://github.com/AragonBlack/fundraising.git -b next;
cd fundraising;
npm run bootstrap -- --no-ci;
cd ..;
