#!/bin/bash

set -e;

echo "Fetching planning-suite and installing dependencies (this may take a while 😉)"

cd repos;
git clone https://github.com/AutarkLabs/open-enterprise.git -b dev;
cd open-enterprise;
npm run bootstrap -- --no-ci;
cd ..;
