#!/bin/bash

DIR=$(pwd)
IPFS_CACHE=$DIR/ipfs-cache

set -e;

cd repos/fundraising;

LERNA_EXEC_APPS="npx lerna exec --scope=@ablack/fundraising-aragon-fundraising --concurrency=1 --stream"
LERNA_EXEC_APPS_WITHOUT_UI="npx lerna exec --scope=@ablack/fundraising-bancor-formula --scope=@ablack/fundraising-batched-bancor-market-maker --scope=@ablack/fundraising-tap --concurrency=1 --stream"

$LERNA_EXEC_APPS -- "aragon apm publish 1.0.0 --files app/build --publish-dir $IPFS_CACHE/\$LERNA_PACKAGE_NAME --skip-confirmation --no-propagate-content"
$LERNA_EXEC_APPS_WITHOUT_UI -- "aragon apm publish 1.0.0 --publish-dir $IPFS_CACHE/\$LERNA_PACKAGE_NAME --skip-confirmation --no-propagate-content"