#!/bin/bash

set -e;
source scripts/set-env;

echo "Make sure you are on an empty chain running with the default mnemonic"
sleep 2; # let the people read

echo "Deploying ENS instance"
npx truffle compile;
DEPLOYED_ENS=$(npx truffle exec --network rpc scripts/deploy/test-ens.js | tail -n 1)
if [ "${ENS}" = "${DEPLOYED_ENS}" ]; then
	echo "ENS deployed $DEPLOYED_ENS"
else
	echo >&2 "ENS address missmatch. Please restart ganache by running:";
	echo "npm run start-ganache";
	rm -rf aragon-ganache;
	exit 1;
fi

echo "Deploying APM registry to aragonpm.eth and open.aragonpm.eth"
npx truffle exec --network rpc scripts/deploy/apm-open.js

echo "Deploying aragonID registry to aragonpm.eth"
npx truffle exec --network rpc scripts/deploy/beta-aragonid.js;

echo "Deploying Minime factory"
npx truffle exec --network rpc scripts/deploy/minimefactory.js;