#!/bin/bash

set -e;
echo "Cleaning and creating 'repos' dir"
rm -rf repos;
mkdir repos;
cd repos;

echo "Fetching aragonOS and installing dependencies..."
git clone git@github.com:aragon/aragonOS -b v3.1.8;
cd aragonOS;
npm i;
cd ..;

echo "Fetching aragon-id and installing dependencies..."
git clone git@github.com:aragon/aragon-id -b master;
cd aragon-id;
npm i;
cd ..;

echo "Fetching dao-kits and installing dependencies (this may take a while 😉)"
git clone git@github.com:aragon/dao-kits.git -b master;
cd dao-kits;
npm i;
