#!/bin/bash

set -e;
echo "Cleaning and creating 'repos' dir"
rm -rf repos;
mkdir repos;
cd repos;

echo "Fetching aragon-apps and installing dependencies (this may take a while 😉)"

git clone https://github.com/aragon/aragon-apps.git -b master;
cd aragon-apps;
INSTALL_FRONTEND=true npm i;
cd ..;

echo "Fetching planning-suite and installing dependencies (this may take a while 😉)"
git clone https://github.com/AutarkLabs/open-enterprise.git -b dev;
cd open-enterprise;
npm i;
cd ..;

echo "Fetching fundraising and installing dependencies (this may take a while 😉)"
git clone https://github.com/AragonBlack/fundraising.git -b next;
cd fundraising;
npm i;
cd ..;

echo "Fetching dao-templates and installing dependencies (this may also take a while 😉)"
git clone https://github.com/aragon/dao-templates.git -b master;
cd dao-templates;
npm i;
cd ..;

echo "Fetching aragon client and installing dependencies"
git clone https://github.com/aragon/aragon.git -b master;
cd aragon;
npm i;