#!/bin/bash

set -e;
echo "Cleaning and creating 'repos' dir"
rm -rf repos;
mkdir repos;

cd repos

echo "Linking to local repos"
ln -s ../../aragon-apps aragon-apps
ln -s ../../open-enterprise open-enterprise
ln -s ../../fundraising fundraising
ln -s ../../dao-templates dao-templates
ln -s ../../aragon aragon
