#!/bin/bash

DIR=$(pwd)
IPFS_CACHE=$DIR/ipfs-cache

source scripts/set-env;

set -e;
cd repos/dao-kits;

LERNA_EXEC="npx lerna exec --scope=@aragon/templates-bare --scope=@aragon/templates-democracy --scope=@aragon/templates-multisig --scope=@aragon/templates-trust --concurrency=1 --stream"

$LERNA_EXEC -- "aragon apm publish 1.0.0 $(npm run deploy:rpc | tail -n 1) --files manifest.json --publish-dir $IPFS_CACHE/\$LERNA_PACKAGE_NAME --skip-confirmation --no-propagate-content"