#!/bin/bash

rm -rf published-apps;
mkdir published-apps;
set -e;

cd repos/aragon-apps;
cd apps/voting;

npm link @aragon/cli
npx apm version 1.0.0 --network rpc
npx apm publish --network rpc --no-ipfs-check --files app/build --publish-dir ../../../../published-apps/"$(../../../../scripts/rand)" --apm.ipfs.rpc "http://ipfs.aragon.network:5001"

cd ../token-manager;
npm link @aragon/cli
npx apm version 1.0.0 --network rpc
npx apm publish --network rpc --no-ipfs-check --files app/build --publish-dir ../../../../published-apps/"$(../../../../scripts/rand)" --apm.ipfs.rpc "http://ipfs.aragon.network:5001"

cd ../finance;
npm link @aragon/cli
npx apm version 1.0.0 --network rpc
npx apm publish --network rpc --no-ipfs-check --files app/build --publish-dir ../../../../published-apps/"$(../../../../scripts/rand)" --apm.ipfs.rpc "http://ipfs.aragon.network:5001"

cd ../vault;
npm link @aragon/cli
npx apm version 1.0.0 --network rpc
npx apm publish --network rpc --no-ipfs-check --files app/build --publish-dir ../../../../published-apps/"$(../../../../scripts/rand)" --apm.ipfs.rpc "http://ipfs.aragon.network:5001"

