#!/bin/bash

DIR=$(pwd)
IPFS_CACHE=$DIR/ipfs-cache

rm -rf $IPFS_CACHE;
mkdir $IPFS_CACHE;

set -e;
cd repos/aragon;

npm run build:local;

aragon apm publish 1.0.0 --only-content --files build --publish-dir $IPFS_CACHE/@aragon/aragon --skip-confirmation --no-propagate-content --no-build;
