#!/bin/bash

DIR=$(pwd)
IPFS_CACHE=$DIR/ipfs-cache

set -e;

cd repos/open-enterprise;

LERNA_EXEC_APPS="npx lerna exec --scope=@tps/apps-address-book --scope=@tps/apps-allocations --scope=@tps/apps-dot-voting --scope=@tps/apps-projects --scope=@tps/apps-rewards --concurrency=1 --stream"

$LERNA_EXEC_APPS -- "aragon apm publish 1.0.0 --files dist --publish-dir $IPFS_CACHE/\$LERNA_PACKAGE_NAME --skip-confirmation --no-propagate-content"