#!/bin/bash

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
mnemonic=$(node -p "require(require('path').join(\"${SCRIPTPATH}\", '../src/ganache-vars')).MNEMONIC")

rm -rf aragon-ganache
mkdir aragon-ganache
set -e;
npx ganache-cli -m "${mnemonic}" -i 15 -l 100000000 --db aragon-ganache
