#!/bin/bash

BASEPATH="$( dirname "$(dirname "$0")" )"
mnemonic=$(node -p "require(require('path').join(\"${SCRIPTPATH}\", '../src/ganache-vars')).MNEMONIC")

cd "$BASEPATH"
rm -rf aragon-ganache
mkdir aragon-ganache
set -e;
npx ganache-cli -m "${mnemonic}" -i 15 -l 100000000 --db aragon-ganache
